# Generated by Django 4.2.30 on 2026-05-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('shortDescription', models.CharField(max_length=256)),
                ('longDescription', models.TextField()),
                ('dietType', models.CharField(choices=[('VEGAN', 'VEGAN'), ('VEGETARIAN', 'VEGETARIAN'), ('KETO', 'KETO'), ('NONE', 'NONE')], default='NONE', max_length=20)),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('brandId', models.IntegerField()),
                ('brandName', models.CharField(max_length=35)),
                ('rating', models.IntegerField()),
                ('originalPrice', models.IntegerField()),
                ('discountPrice', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foods/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food.food')),
            ],
        ),
    ]
